FROM nginx:1.19

COPY nginx/nginx.conf /etc/nginx/templates/default.conf.template

WORKDIR /var/www

COPY nginx/index.html ./html/
COPY dist/client/ ./static/client/
COPY dist/django/ ./static/django/
