version: "3"
services:
    django:
        build:
            dockerfile: docker/Dockerfile.django
            context: ..
        command: "/bin/sh -c '\
            poetry run ./wait_for_postgres.py && \
            poetry run gunicorn -b 0.0.0.0:80 -t 4 config.wsgi'"
        env_file: prod.env
        depends_on:
            - db
        volumes:
            - /var/CHANGEME/prod/uploads/:/var/uploads/
    parcel:
        build:
            dockerfile: docker/Dockerfile.parcel
            context: ..
        command: "yarn run build"
        volumes:
            - ../dist/client/:/build/dist/
    nginx:
        build:
            dockerfile: docker/Dockerfile.nginx
            context: ..
        environment:
            # Use the normal nginx host var for production.
            - DJANGO_HOST=$host
        depends_on:
            - django
        ports:
            - 8000:80
        volumes:
            - /var/CHANGEME/prod/uploads/:/var/www/static/uploads:ro
    db:
        image: postgres:11
        env_file: prod.env
